### PR TITLE
#163: new BTC adapter

### PR DESCRIPTION
**Pull request by yegor256**
Let's merge...

See #163

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#212](https://github.com/zold-io/wts.zold.io/issues/212) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#212](https://github.com/zold-io/wts.zold.io/issues/212); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#212` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#212](https://github.com/zold-io/wts.zold.io/issues/212) is now out of scope

**Pull request merged**
